### PR TITLE
Introduce linting with ESLint 

### LINKED ISSUE #9: Introduce linting with ESLint
[ESLint](https://eslint.org/) is a tool that helps us write more consistent code, regardless of individual.

We should introduce it into CC to prevent nits!

We can take inspiration from this [.eslintrc.yml](https://github.com/humphd/next/blob/master/.eslintrc.yml) configuration along with adding commands to [view and fix linting issues](https://github.com/humphd/next/blob/912afdc77ebdb57798c3de58b46d1d2c80873c07/package.json#L19-L20).

We'd need to install the following dev dependencies:

* `eslint`
* `eslint-config-prettier`
* `eslint-plugin-prettier`
* `prettier`

### PR DESCRIPTION
**Pull request by SeanPrashad**
Fixes #9: Introduce linting with ESLint 

This PR introduces a number of tools that will help normalize our codebase, no matter whose authoring new or existing code.

It uses [ESLint](https://eslint.org/), a linter for JavaScript in combination with [Prettier](https://prettier.io/) and [Pretty-Quick](https://www.npmjs.com/package/pretty-quick). Prettier will automatically format code according to the rules specified in our `.eslintrc`. I've gone ahead and overridden some of Prettier's defaults (like using `"` instead of `'` where applicable) within `.prettierrc`.

`Pretty-Quick` will format files on commit that differ from the respective version in the `master` branch. This means that if an author accidentally touches code without meaning to, it will format the files back to how it is on the `master` branch. In essence, this will minimize nits during PR reviews, meaning that we can focus more on 🚢 ing great features for CC instead of worrying about semi-colons and new line characters 🎉

### CODE REVIEW

**Comment by SeanPrashad** [comment]
GIF of Pretty-Quick in action [here](https://imgur.com/a/1QA6KSJ)!

**Comment by SeanPrashad** [comment]
Thanks for the heads up @klymenkoo - removed it!

**Comment by SeanPrashad** [comment]
@Mera-Gangapersaud I've added the Prettier badge:

image

**Comment by Mera-Gangapersaud** [comment]
Thanks 😄

**Pull request merged**
